### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [01org/tinycrypt#1]
I would like to point out that identifiers like "[`__TC_AES_H__`](https://github.com/01org/tinycrypt/blob/e100a0dbbc5abd2ccdbfe56b3d4e2cb3a47c841f/lib/aes.h#L45)" and "[`__TC_UTILS_H__`](https://github.com/01org/tinycrypt/blob/382b6be10ed053a551b6c5cf127a7a58d372bb8f/lib/utils.h#L35)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by hackermnementh** [comment]
Won't fix. Not supporting C++ usage.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
