### ISSUE TITLE
constants.h defines a variable where it should define a type

### ISSUE THREAD

**Issue by mazen-neifer** [01org/tinycrypt#16]
Lines 50..52 of `contants.h `try to define `bool` type as follows:
```C
#ifndef bool
enum {false, true} bool;
#endif
```
There are several issues with the above code, that causes multiple definitions of the same symbol linker error on some strict linkers.

1. The above definition, besides it defines the two unnamed enum elements `treu` and `false`, defines a variable `bool`. The right way would be using `typedef` keyword
2. The defined variable `bool` does not define the pre-processor symbol `bool`, so it does not make sense to enclose the definition

It is probably better to either include `stdbool.h' or copy its content:
```C
#ifndef bool
#ifndef __cplusplus
#define bool   _Bool
#define true   1
#define false  0
#endif
#endif
```

PS: This issue was open du to https://gerrit.zephyrproject.org/r/#/c/10848

**Comment by hackermnementh** [comment]
Would rather copy the content of stdbool.h and reduce the need for unnecessary headers.

**Comment by mazen-neifer** [comment]
Generally one tries to reduce code duplication. I don't recommend this.

**Comment by hackermnementh** [comment]
Pulled out of constants.h in latest commit.
