### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [01org/tinycrypt#2]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/01org/tinycrypt/blob/1691f2b164fb5ff1e32265d6df643fc8b33cf112/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by hackermnementh** [comment]
Suggestion noted. Will revisit at a later date.
