### ISSUE TITLE
p-256 (Only Curve used in ECC) is under suspicion / maybee unsecure

### ISSUE THREAD

**Issue by baw-serafin** [01org/tinycrypt#33]
https://safecurves.cr.yp.to/

**Comment by mczraf** [comment]
@baw-serafin Curve p-256 is a curve standardized by NIST and likely the most widely-deployed elliptic curve in use nowadays. Prof. Bernstein's proposes his particular set of metrics to define what is a safe curve and what is not. To this date, there are no successful attacks demonstrated against p-256 in the literature. Removing support to NIST p-256 would be unreasonable at this point.

**Comment by baw-serafin** [comment]
@mczraf Did not state it should be removed. As it is widely deployed at the moment it probably makes sense to support the curve.
BUT, I would propose:
 * It should not be the only choice
* There should be some warning / hint in the documentation
* Another curve should be the default
