### ISSUE TITLE
tc_ctr_prng_reseed() bug?

### ISSUE THREAD

**Issue by bnusbick** [01org/tinycrypt#5]
It appears to me that tc_ctr_prng_reseed() in ctr_prng.c has a bug().  I believe the following:
		/* 10.2.1.4.1 step 4 */
		tc_ctr_prng_update(ctx, entropy);

Should be:
		/* 10.2.1.4.1 step 4 */
		tc_ctr_prng_update(ctx, seed_material);

**Comment by chris-morrison** [comment]
Thanks for raising this - I have submitted a branch to address the issue.

Best regards,
Chris
